#!/usr/bin/env php
<?php

set_time_limit(0);

$app = require_once __DIR__.'/src/bootstrap.php';

$cli = $app['console'];
$cli->add(new \LaFourchette\Console\Check());
$cli->add(new \LaFourchette\Console\Status());
$cli->add(new \LaFourchette\Console\Create());
$cli->add(new \LaFourchette\Console\Delete());
$cli->add(new \LaFourchette\Console\Reset());
$cli->add(new \LaFourchette\Console\Stop());
$cli->add(new \LaFourchette\Console\Start());
$cli->run();
